name: s3upload
description: 'Upload files to s3, in multiple part mode'
inputs:
  file:
    description: 'File to upload'
    required: true
    default: '*'
  max_cur:
    description: 'Max number of parallel tasks'
    required: true
    default: 20
  s3path:
    description: 'S3 path to upload to'
    required: true
    default: 'cf-buildpacks-bucket'
outputs:
  filelist: # id of output
    description: 'File list uploaded'
runs:
  using: 'node16'
  main: 'index.js'
